In [10]:
import numpy as np

my_list = list(range(1000000))
my_array = np.arange(1000000)

In [9]:
%timeit my_list2 = [i * 2 for i in my_list]
%timeit my_array2 = my_array * 2

54.3 ms ± 1.83 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
2.05 ms ± 124 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
a = [
    [1,1.2,3],
    [-123,123,0]
]
data = np.array(a)
print(data)

[[   1.     1.2    3. ]
 [-123.   123.     0. ]]


In [15]:
# 0차원 : 스칼라(scala), 1차원 : 벡터(vector)
# 2차원 : 행렬(matrix), 3차원 : 텐서(tenser)
print(data * 10)
print(data+ data)

[[   10.    12.    30.]
 [-1230.  1230.     0.]]
[[   2.     2.4    6. ]
 [-246.   246.     0. ]]


In [16]:
print(data.shape)
print(data.dtype)

(2, 3)
float64


## ndarray 생성하기

In [19]:
data1 = [1, 2, 3, 4, 5]
arr1 = np.array(data1)
print(arr1)
print(type(arr1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [24]:
arr2 = np.array([[1.1, 2.2],[3.3, 4.4]])
print(arr2)
print(type(arr2))

[[1.1 2.2]
 [3.3 4.4]]
<class 'numpy.ndarray'>


In [26]:
print(arr1.ndim)  #배열의 차원을 보여줌
print(arr2.ndim)

1
2


In [27]:
print(arr1.shape)
print(arr2.shape)

(5,)
(2, 2)


In [32]:
print(np.zeros(10))
print([0] * 10)
print(np.zeros((5,5)))
print(np.empty((2,2,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [33]:
print(np.arange(10)) #0부터 순서대로 배열

[0 1 2 3 4 5 6 7 8 9]


### ndarray 자료형

In [35]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)

print(arr1.dtype)
print(arr2.dtype)

float64
int32


In [38]:
arr1 = np.array([1, 2, 3])
print(arr1.dtype)
float_arr1 = arr1.astype(np.float64) #타입 바꾸고 싶을 때
print(float_arr1)
print(float_arr1.dtype)

int64
[1. 2. 3.]
float64


In [42]:
arr2 = np.array([1.1, 2.2, 3.3, 9.9])
print(arr2.dtype)
int_arr2 =arr2.astype(np.int64)
print(int_arr2)
print(int_arr2.dtype)

float64
[1 2 3 9]
int64


## 산술 연산

In [48]:
arr = np.array ([[1,2,3],[4,5,6]])
print(arr)
print(arr * arr)
print(arr + arr)
print(1 / arr)
print (arr*3)

[[1 2 3]
 [4 5 6]]
[[ 1  4  9]
 [16 25 36]]
[[ 2  4  6]
 [ 8 10 12]]
[[1.         0.5        0.33333333]
 [0.25       0.2        0.16666667]]
[[ 3  6  9]
 [12 15 18]]


In [52]:
arr2 = np.array([[3,2,1], [1,2,3]])
print(arr)
print(arr2)
print(arr > arr2)
print (arr == 3)

[[1 2 3]
 [4 5 6]]
[[3 2 1]
 [1 2 3]]
[[False False  True]
 [ True  True  True]]
[[False False  True]
 [False False False]]


## 색인(인덱싱)과 슬라이싱

In [57]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [58]:
print(arr[7])
print(arr[2:5])

7
[2 3 4]


In [59]:
arr[2:5] = 10
print(arr)

[ 0  1 10 10 10  5  6  7  8  9]


In [60]:
py_list = [1, 2, 3, 4, 5]
py_list[2:3].pop()
print(py_list)

[1, 2, 3, 4, 5]


In [62]:
#2차원 연습
arr = np.array([[1, 2, 3], [4, 5, 6]]) #[1,2,3]은 0번째 [4,5,6]은 1번째
print(arr)

[[1 2 3]
 [4 5 6]]


In [65]:
print(arr[1][1])
print(arr[1,1])

5
5


In [67]:
#3차원 연습
arr3d = np.array([[[1,2,3],[4,5,6],[7,8,9]],
         [[11,12,13],[14,15,16],[17,18,19]], 
         [[11,22,33],[44,55,66],[77,88,99]]])

In [69]:
print(arr3d[2][0][1])
print(arr3d[2,0,1])

22
22


In [72]:
arr3d[:1,1:, 2:]

array([[[6],
        [9]]])

In [73]:
arr3d[0,1:, 2:]

array([[6],
       [9]])

In [74]:
arr3d[0, 1:, 2:] = 9999
print(arr3d)

[[[   1    2    3]
  [   4    5 9999]
  [   7    8 9999]]

 [[  11   12   13]
  [  14   15   16]
  [  17   18   19]]

 [[  11   22   33]
  [  44   55   66]
  [  77   88   99]]]


## 불리언 값으로 선택

In [79]:
names = np.array(['hong','kim','hong','kim'])
data = np.array([['math',60], ['math',90], ['eng', 70], ['eng',50]])

In [80]:
names == 'hong'

array([ True, False,  True, False])

In [81]:
#data[[True, False, True, False]]
data[names == 'hong']

array([['math', '60'],
       ['eng', '70']], dtype='<U21')

In [83]:
print(data[names == 'hong', 1])
print(data[names == 'hong' , :1])

['60' '70']
[['math']
 ['eng']]


In [86]:
print(names != 'hong')
print(~(names == 'hong'))

[False  True False  True]
[False  True False  True]


In [87]:
cond = names == 'kim'
data[cond]

array([['math', '90'],
       ['eng', '50']], dtype='<U21')

## 팬시 색인(fancy indexing)

In [89]:
arr = np.zeros((8, 4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [90]:
arr[[4, 3, 0, 5]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [5., 5., 5., 5.]])

In [91]:
arr[[-3, -5, -1]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [7., 7., 7., 7.]])

In [96]:
arr = np.arange(32).reshape(8,4) #행렬의 가로세로 배열을 변경하고 싶을 때
# print(arr)

In [99]:
arr[[1, 5], [2, 3]]

array([ 6, 23])

In [100]:
arr[[1, 5]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23]])

In [101]:
arr[[1, 5]][:, [2,3]]

array([[ 6,  7],
       [22, 23]])

## 배열 전치

In [103]:
arr = np.arange(15).reshape(3, 5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [104]:
print(arr. T)

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [108]:
# 행렬의 내적, 곱
print(arr @ arr.T)
print(np.dot(arr, arr.T))

[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]
[[ 30  80 130]
 [ 80 255 430]
 [130 430 730]]


## numpy 함수

In [110]:
samples = np.random.standard_normal(size=(3,3))
print(samples)

[[ 0.81739198  0.88157253  0.57164712]
 [ 0.09803293 -2.16033265 -0.40335982]
 [ 0.51651107 -0.67885978 -0.99544178]]


In [113]:
arr1 = np.sqrt(samples)
print(arr1)
#루트 씌울 때 음수는 nan 으로 뜸

[[0.90409733 0.93892094 0.75607349]
 [0.3131021         nan        nan]
 [0.71868705        nan        nan]]


C:\Users\1-22\AppData\Local\Temp\ipykernel_12840\2844927003.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr1 = np.sqrt(samples)


In [116]:
arr2 =np.abs(samples) #절댓값으로 바꿈
print(arr2)

[[0.81739198 0.88157253 0.57164712]
 [0.09803293 2.16033265 0.40335982]
 [0.51651107 0.67885978 0.99544178]]


In [117]:
np.isnan(arr1)

array([[False, False, False],
       [False,  True,  True],
       [False,  True,  True]])